---
- name: Install required packages
  apt:
    name: curl
    update_cache: yes
    state: latest

- name: Add the NodeSource repository to the system
  shell: curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -

- name: Install NodeJS and Npm
  apt:
    name: nodejs
    update_cache: yes
    state: latest

- name: Update Npm to latest version
  command: npm install -g npm
